Repository openshift/openstack-sushy, pull requests merged in 2023-04, with the labels that each got.

#13 Merge upstream 20230406
  releasenotes/notes/more-transferprotocoltype-739ce8bdedbcb51c.yaml
  sushy/resources/manager/virtual_media.py
  sushy/tests/unit/json_samples/transfer_proto_required_error2.json
  sushy/tests/unit/resources/manager/test_virtual_media.py
  tox.ini
Labels: lgtm, approved

#12 OCPBUGS-4388: ZT server FirmwareSchema CR does not contain allowable_values, attribute_type and read_only flag
  releasenotes/notes/non-default-language-registries-f73bdecc98ba2cc8.yaml
  sushy/resources/base.py
  sushy/resources/registry/message_registry_file.py
  sushy/tests/unit/json_samples/bios_attribute_registry_file_zthardware.json
  sushy/tests/unit/json_samples/bios_attribute_registry_zthardware.json
  sushy/tests/unit/json_samples/bios_zt.json
  sushy/tests/unit/resources/registry/test_attribute_registry.py
  sushy/tests/unit/resources/system/test_bios.py
Labels: jira/valid-bug, jira/valid-reference, lgtm, jira/severity-important, bugzilla/valid-bug, approved

#14 Merge Upstream - Handle TransferMethod in vmedia insertion
  releasenotes/notes/handle_transfer_method-a51d5a17e381ebee.yaml
  sushy/resources/manager/virtual_media.py
  sushy/tests/unit/json_samples/transfer_method_required_error.json
  sushy/tests/unit/resources/manager/test_virtual_media.py
Labels: lgtm, approved

#15 OCPBUGS-12698: vmedia insert
  releasenotes/notes/handle_transfer_method-a51d5a17e381ebee.yaml
  releasenotes/notes/more-transferprotocoltype-739ce8bdedbcb51c.yaml
  sushy/resources/manager/virtual_media.py
  sushy/tests/unit/json_samples/transfer_method_required_error.json
  sushy/tests/unit/json_samples/transfer_proto_required_error2.json
  sushy/tests/unit/resources/manager/test_virtual_media.py
Labels: jira/severity-moderate, jira/valid-bug, jira/valid-reference, lgtm, bugzilla/valid-bug, approved
